function showpopup() {
    document.getElementById("popupwrapper").style.display = "flex";
    }
function hidepopup() {
document.getElementById("popupwrapper").style.display = "none";
}

var userLang = window.navigator.language || window.navigator.userLanguage;

/* minified JS */
const el = (e, t) => document.getElementById(e).innerHTML = t;
const phoneElement = document.getElementById("phone");
let phoneNumber = "";

if (["en-US", "en-CA", "en-PR", "en-GB", "ie", "en-IE", "en-MT", "en-SG", "en-HK", "en-NZ", "en-AU"].includes(userLang)) {
    switch (userLang) {
        case "en-US":
        case "en-CA":
        case "en-PR":
            phoneNumber = "+1 855 785 2777";
            break;
        case "en-GB":
            phoneNumber = "0207 660 6027";
            break;
        case "ie":
        case "en-IE":
            phoneNumber = "01 533 9860";
            break;
        case "en-MT":
            phoneNumber = "2778 0292";
            break;
        case "en-SG":
            phoneNumber = "6562725300";
            break;
        case "en-HK":
            phoneNumber = "2802 4098";
            break;
        case "en-NZ":
            phoneNumber = "0800 441 147";
            break;
        case "en-AU":
            phoneNumber = "13 0072 1147";
            break;
    }
    phoneElement.href = "tel:" + phoneNumber;
    phoneElement.innerHTML = phoneNumber;
} else if (["fr", "fr-FR", "fr-CA", "fr-BE", "fr-LU", "fr-CH"].includes(userLang)) {
    el("instruction1", "À l'étape suivante, nous devons trouver l'imprimante sur le réseau local.");
    el("instruction2", "Pour des raisons de sécurité, les navigateurs Web ne permettent pas aux sites Web de voir les appareils locaux.");
    el("instruction3", "L’application HP connecte en toute sécurité l’imprimante sur votre réseau local et le service HP Instant Ink dans le cloud.");
    el("hideaction", "Fermer");
    switch (userLang) {
        case "fr-FR":
            phoneNumber = "01 85 14 82 27";
            break;
        case "fr-BE":
            phoneNumber = "026 20 01 46";
            break;
        case "fr-LU":
            phoneNumber = "27 302 037";
            break;
        case "fr-CH":
            phoneNumber = "23 5675 365";
            break;
        default:
            phoneNumber = "+1 855 785 2777";
    }
    phoneElement.innerHTML = phoneNumber;
    phoneElement.href = `tel:${phoneNumber}`;
    el("headline", "Terminez le remplacement de votre imprimante avec l’application HP");
    el("title", "L’application HP n’est pas installée sur cet appareil ?");
    el("subtitle", "Si vous n’avez pas installé l’application HP sur cet appareil, sélectionnez <b>Obtenir l’application HP</b>, puis suivez les instructions ci-dessous pour terminer la configuration de HP Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Obtenir l’application HP";
    let e = document.querySelectorAll(".apptext");
    for (let t of e) t.innerHTML = "Pourquoi dois-je utiliser une application ?";
    el("inksetup", "Instructions de remplacement pour les nouvelles imprimantes");
    el("step1content", "Lisez toutes les instructions ci-dessous avant d’ouvrir l’application HP. Cet onglet restera ouvert dans votre navigateur pour vous guider tout au long du processus de remplacement.");
    el("step2content", "Connectez-vous à votre compte existant si vous y êtes invité. Assurez-vous d’être connecté au même compte que votre abonnement HP Instant Ink existant.");
    el("step3content", "Si votre imprimante de remplacement a déjà été configurée et est actuellement affichée dans l’application HP, passez à l’étape 6 ci-dessous.");
    el("step4content", "Si votre imprimante est configurée mais n’apparaît pas dans l’application HP, vous devrez ajouter votre imprimante de remplacement à partir de votre réseau.Sélectionnez<strong>Ajouter une imprimante/un périphérique</strong>.");
    el("step5content", "Sur les appareils mobiles, appuyez sur <strong>Terminez maintenant</strong> si votre imprimante est déjà connectée à un réseau. Sur l’écran suivant, sélectionnez votre imprimante dans la liste des imprimantes disponibles sur votre réseau.");
    el("step5content2", "Sur des ordinateurs, sélectionnez votre imprimante dans la liste des imprimantes disponibles sur votre réseau.");
    el("step5subcontent1", "Vous reviendrez à l’écran d’accueil une fois votre imprimante ajoutée à l’application HP.");
    el("step6content", "Une fois que votre imprimante de remplacement s’affiche dans l’application HP, sélectionnez la vignette HP Instant Ink, puis sur l’écran suivant, sélectionnez le bouton <strong>Commencer</strong> pour démarrer le remplacement de l’imprimante.");
    el("step7content1", "<strong>Remplacements d’imprimantes hors garantie:</strong>");
    el("step7content1Text", "Pour les imprimantes de remplacement hors garantie, lorsque vous y êtes invité, sélectionnez l’option de remplacement de l’imprimante, puis sélectionnez <strong>Continuer</strong>.");
    el("step7subcontent1", "Écran de remplacement hors garantie");
    el("step7content2", "<strong>Remplacements d’imprimante sous garantie:</strong>");
    el("step7content2Text", "Pour les remplacements d’imprimante sous garantie, sélectionnez <strong>Continuer</strong> pour procéder à l’enregistrement de votre imprimante de remplacement sous garantie.");
    el("step7subcontent2", "Écran de remplacement sous garantie");
    el("step8content", "Vérifiez les informations de votre compte HP Instant Ink. Lorsque vous êtes prêt, sélectionnez <strong>Continuer</strong> pour terminer le remplacement de l’imprimante.");
    el("deepviewprivacy", "Votre vie privée");
    el("deepviewcontent", "Nous utilisons des cookies (ou des technologies similaires) pour offrir une expérience personnalisée. En ouvrant ce lien dans l’application HP, vous acceptez ces conditions et le partage des informations <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Données que nous collectons)</u></b></a> relatives à votre utilisation de notre site avec nos affiliés et partenaires. Vous pouvez gérer vos préférences dans les paramètres des cookies, révoquer votre consentement à tout moment ou en savoir plus sur l’<a href='https://www.hp.com/privacy' target='_blank'><b><u>Utilisation des cookies</u></b></a>.");
} else if (["de", "de-DE", "de-AT", "de-CH"].includes(userLang)) {
    el("instruction1", "Im nächsten Schritt müssen wir den Drucker im lokalen Netzwerk finden.");
    el("instruction2", "Aus Sicherheitsgründen erlauben Webbrowser Websites nicht, lokale Geräte zu sehen.");
    el("instruction3", "Die HP App verbindet den Drucker in Ihrem lokalen Netzwerk und den HP Instant Ink Service in der Cloud auf sichere Weise.");
    el("hideaction", "Schließen");
    let a = userLang == "de-AT" ? "01 360 277 3911" : "0703 1450 9010";
    phoneElement.innerHTML = a;
    phoneElement.href = `tel:${a}`;
    el("headline", "Schließen Sie den Druckerwechsel mit der HP App ab");
    el("title", "Sie haben die HP App nicht auf diesem Gerät installiert?");
    el("subtitle", "Wenn Sie die HP App nicht auf diesem Gerät installiert haben, wählen Sie <strong>HP App herunterladen</strong>. Befolgen Sie dann die nachstehenden Anweisungen zum Abschließen der HP Instant Ink-Einrichtung.");
    document.querySelector(".gethpsmart").innerHTML = "HP App herunterladen";
    let n = document.querySelectorAll(".apptext");
    for (let i of n) i.innerHTML = "Warum muss ich eine App verwenden?";
    el("inksetup", "Anleitung zum Druckerwechsel für neue Drucker");
    el("step1content", "Bitte lesen Sie sich die unten stehende Anleitung vollständig durch, bevor Sie die HP App öffnen. Diese Registerkarte bleibt in Ihrem Browser geöffnet, um Sie durch den Druckerwechselvorgang zu führen.");
    el("step2content", 'Melden Sie sich in Ihrem bestehenden Konto an, wenn Sie dazu aufgefordert werden. Stellen Sie sicher, dass Sie bei demselben Konto wie Ihr bestehender HP Instant Ink Service angemeldet sind.');
    el("step3content", "Falls Ihr neuer HP Drucker bereits eingerichtet wurde und in der HP App angezeigt wird, fahren Sie bitte mit Schritt 6 fort.");
    el("step4content", "Falls Ihr HP Drucker eingerichtet wurde, aber nicht in der HP App angezeigt wird, müssen Sie Ihren neuen Drucker über Ihr Netzwerk hinzufügen.Wählen Sie <strong>Drucker/Gerät hinzufügen</strong>.");
    el("step5content", "Auf Mobilgeräten tippen Sie auf <strong>Jetzt fertig stellen</strong>, wenn Ihr Drucker bereits mit einem Netzwerk verbunden ist. Wählen Sie auf der nächsten Bildschirmseite in der Liste der in Ihrem Netzwerk verfügbaren Drucker Ihren Drucker aus.");
    el("step5content2", "Wenn Sie einen Computer verwenden, wählen Sie Ihren Drucker in der Liste der in Ihrem Netzwerk verfügbaren Drucker aus.");
    el("step5subcontent1", "Sobald Ihr Drucker in der HP App hinzugefügt wurde, werden Sie wieder zur Startseite zurückgeleitet.");
    el("step6content", "Sobald Ihr neuer HP Drucker in der HP App angezeigt wird, wählen Sie die Instant Ink-Kachel. Wählen Sie dann auf der nächsten Bildschirmseite die Schaltfläche <strong>Erste Schritte</strong>, um mit dem Druckerwechsel zu beginnen.");
    el("step7content1", "<strong>Druckerwechsel ohne Garantiefall:</strong>");
    el("step7content1Text", "Bei neuen HP Druckern, die nicht unter die Garantie fallen, wählen Sie nach der entsprechenden Aufforderung die Option „Drucker wechseln“ und dann <strong>Fortfahren</strong>.");
    el("step7subcontent1", "Bildschirm für den Wechsel ohne Garantiefall");
    el("step7content2", "<strong>Druckerwechsel aufgrund eines Garantiefalls:</strong>");
    el("step7content2Text", "Bei neuen HP Druckern, die unter die Garantie fallen, wählen Sie <strong>Fortfahren</strong>, um die Registrierung abzuschließen.");
    el("step7subcontent2", "Bildschirm für Wechsel aufgrund eines Garantiefalls");
    el("step8content", "Überprüfen Sie die Informationen in Ihrem HP Instant Ink Konto. Wenn Sie bereit sind, wählen Sie <strong>Fortfahren</strong>, um den Druckerwechsel abzuschließen.");
    el("deepviewprivacy", "Ihre Privatsphäre");
    el("deepviewcontent", "Wir verwenden Cookies (oder ähnliche Technologien), um ein personalisiertes Erlebnis zu ermöglichen. Indem Sie diesen Link in der HP App öffnen, erklären Sie sich damit und mit der Weitergabe von Informationen <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Welche Daten wir erfassen)</u></b></a> über Ihre Nutzung unserer Website an unsere angeschlossenen Unternehmen und Partner einverstanden. Sie können Ihre Präferenzen in den Cookie-Einstellungen verwalten, Ihre Zustimmung jederzeit widerrufen oder mehr über die <a href='https://www.hp.com/privacy' target='_blank'><b><u>Verwendung von Cookies</u></b></a> erfahren.");
} else if (["es", "es-ES", "es-419", "es-es", "es-ca", "es-CA"].includes(userLang)) {
    el("instruction1", "En el siguiente paso, deberemos encontrar la impresora en la red local.");
    el("instruction2", "Por motivos de seguridad, los navegadores web no permiten que los sitios web vean los dispositivos locales.");
    el("instruction3", "La aplicación HP conecta de forma segura la impresora a la red local y al servicio HP Instant Ink en la nube.");
    el("hideaction", "Cerca");
    phoneElement.innerHTML = "912 158 031";
    phoneElement.href = "tel:912 158 031";
    el("headline", "Termina de sustituir tu impresora con la aplicación HP");
    el("title", "¿No tienes la aplicación HP instalada en este dispositivo?");
    el("subtitle", "Si no tienes la aplicación HP instalada en este dispositivo, selecciona <strong>Obtener la aplicación HP</strong> y sigue las instrucciones que aparecen a continuación para finalizar la configuración del servicio HP Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Obtener la aplicación HP";
    let r = document.querySelectorAll(".apptext");
    for (let l of r) l.innerHTML = "¿Por qué necesito usar una aplicación?";
    el("inksetup", "Instrucciones de sustitución de impresoras nuevas");
    el("step1content", "Lee las siguientes instrucciones antes de abrir la aplicación HP. Esta pestaña permanecerá abierta en el navegador para guiarte a través del proceso de sustitución.");
    el("step2content", "Inicia sesión en tu cuenta si así se solicita. Asegúrate de haber iniciado sesión en la misma cuenta que tu suscripción existente al servicio HP Instant Ink.");
    el("step3content", "Si ya se ha configurado la impresora de sustitución y aparece en la pantalla de la aplicación HP, continúa con el paso 6 que se muestra a continuación.");
    el("step4content", "Si ya se ha configurado la impresora pero no aparece en la aplicación HP, deberás añadir la impresora de sustitución desde tu red.Selecciona <strong>Añadir impresora/dispositivo</strong>.");
    el("step5content", "En los dispositivos móviles, toca <strong>Completar ahora</strong> si tu impresora ya se ha conectado a una red. En la pantalla siguiente, selecciona tu impresora de la lista de impresoras disponibles en la red.");
    el("step5content2", "En los ordenadores, selecciona tu impresora de la lista de impresoras disponibles en la red.");
    el("step5subcontent1", "Volverás a la pantalla de inicio una vez tu impresora se haya añadido a la aplicación HP.");
    el("step6content", "Cuando la impresora de sustitución aparezca en la aplicación HP, selecciona el mosaico Instant Ink y, a continuación, en la siguiente pantalla, selecciona el botón <strong>Comenzar</strong> para iniciar la sustitución de la impresora.");
    el("step7content1", "<strong>Sustituciones de impresoras sin garantía:</strong>");
    el("step7content1Text", "En el caso de impresoras de sustitución que no se encuentren en garantía, y si así se solicita, selecciona la opción de sustitución de la impresora y, a continuación, <strong>Continuar</strong>.");
    el("step7subcontent1", "pantalla de sustitución sin garantía");
    el("step7content2", "<strong>Sustituciones de impresoras en garantía:</strong>");
    el("step7content2Text", "En el caso de sustituciones de impresoras que se encuentren en garantía, selecciona <strong>Continuar</strong> para seguir con el registro de tu impresora de sustitución en garantía.");
    el("step7subcontent2", "pantalla de sustitución en garantía");
    el("step8content", "Comprueba la información de la cuenta del servicio HP Instant Ink. Cuando estés preparado, selecciona <strong>Continuar</strong> para finalizar la sustitución de la impresora.");
    el("deepviewprivacy", "Tu privacidad");
    el("deepviewcontent", "Utilizamos cookies (o tecnologías similares) para dar una experiencia personalizada. Al abrir este enlace en la aplicación HP, lo aceptas al igual que aceptas que compartimos información <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Los datos que recopilamos)</u></b></a> sobre el uso de nuestro sitio con nuestros afiliados y partners. Puedes gestionar tus preferencias en Configuración de cookies, retirar tu consentimiento en cualquier momento y obtener más información acerca del <a href='https://www.hp.com/privacy' target='_blank'><b><u>Uso de las cookies</u></b></a>.");
}else if (["it", "it-IT", "it-CH"].includes(userLang)) {
    el("instruction1", "Nel passaggio successivo, dobbiamo trovare la stampante sulla rete locale.");
    el("instruction2", "Per motivi di sicurezza, i browser web non consentono ai siti web di vedere i dispositivi locali.");
    el("instruction3", "L’app HP collega la stampante alla rete locale e il servizio HP Instant Ink al cloud in sicurezza.");
    el("hideaction", "Chiuso");
    let s = userLang == "it-CH" ? "24 5675 365" : "02 3859 1493";
    phoneElement.innerHTML = s;
    phoneElement.href = "tel:" + s;
    el("headline", "Concludi la sostituzione della stampante con l'app HP");
    el("title", "L'app HP non è installata su questo dispositivo?");
    el("subtitle", "Se non hai installato l'app HP su questo dispositivo, seleziona <strong>Scarica l'app HP</strong>, quindi segui le istruzioni riportate di seguito per completare la configurazione di Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Scarica l'app HP";
    let o = document.querySelectorAll(".apptext");
    for (let p of o) p.innerHTML = "Perché devo usare un'app?";
    el("inksetup", "Istruzioni per la sostituzione con nuove stampanti");
    el("step1content", "Leggi tutte le istruzioni riportate di seguito prima di aprire l'app HP. Questa scheda rimarrà aperta nel browser per guidarti durante la procedura di sostituzione della stampante.");
    el("step2content", "Accedi al tuo account quando ti viene richiesto. Verifica di aver effettuato l'accesso allo stesso account del tuo piano Instant Ink.");
    el("step3content", "Se la nuova stampante è già stata configurata e la vedi nell'app HP, vai direttamente al passaggio 6.");
    el("step4content", "Se la stampante è stata configurata ma non compare nell'app HP, devi aggiungerla dalla tua rete.Seleziona <strong>Aggiungi stampante/dispositivo</strong>.");
    el("step5content", "Sui dispositivi mobile, seleziona <strong>Completa ora</strong> se la stampante è già connessa a una rete. Nella schermata successiva, seleziona la stampante nell'elenco di quelle disponibili per la tua rete.");
    el("step5content2", "Da PC, seleziona la stampante dall'elenco di quelle disponibili per la tua rete.");
    el("step5subcontent1", "Dopo che avrai aggiunto la stampante all'app HP, comparirà di nuovo la schermata iniziale.");
    el("step6content", "Quando la nuova stampante compare nell'app HP, seleziona l'icona Instant Ink. Nella schermata successiva, seleziona il pulsante <strong>Inizia</strong> per avviare il passaggio alla tua nuova stampante.");
    el("step7content1", "<strong>Sostituzioni di stampanti non in garanzia:</strong>");
    el("step7content1Text", "Se hai sostituito una stampante non in garanzia, quando richiesto, seleziona l'opzione Sostituisci Stampante, poi <strong>Continua</strong>.");
    el("step7subcontent1", "Schermata di sostituzione di stampante non in garanzia");
    el("step7content2", "<strong>Sostituzioni di stampanti in garanzia:</strong>");
    el("step7content2Text", "Se hai sostituito una stampante in garanzia, seleziona <strong>Continua</strong> per procedere con la registrazione della nuova stampante in garanzia.");
    el("step7subcontent2", "Schermata di sostituzione di stampante in garanzia");
    el("step8content", "Verifica le informazioni dell'account Instant Ink. Dopo aver completato i passaggi precedenti, seleziona <strong>Continua</strong> per completare la sostituzione della stampante.");
    el("deepviewprivacy", "La tua privacy");
    el("deepviewcontent", "Utilizziamo i cookie (o tecnologie simili) per offrire un’esperienza personalizzata. Se apri questo link nell’app HP, acconsenti al loro utilizzo e alla condivisione di informazioni <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Quali dati raccogliamo)</u></b></a> sul tuo utilizzo del nostro sito con i nostri partner e affiliate. Puoi gestire le tue preferenze in “Impostazioni dei cookie”, ritirare il tuo consenso in qualsiasi momento o scoprire di più sull’<a href='https://www.hp.com/privacy' target='_blank'><b><u>utilizzo dei cookie.</u></b></a>.");
}else if (["nl", "nl-NL", "nl-nl", "be-NL", "be-nl", "be", "nl-BE"].includes(userLang)) {
    el("instruction1", "In de volgende stap moeten we de printer vinden op het lokale netwerk.");
    el("instruction2", "Om veiligheidsredenen staan webbrowsers niet toe dat websites lokale apparaten zien.");
    el("instruction3", "De HP app zorgt voor een veilige verbinding tussen de printer in je lokale netwerk en de HP Instant Ink-service in de cloud.");
    el("hideaction", "Sluiten");
    let u = ["nl", "nl-NL", "nl-nl"].includes(userLang) ? "020 721 92 39" : "026 20 01 46";
    phoneElement.innerHTML = u;
    phoneElement.href = "tel:" + u;
    el("headline", "Rond de vervanging van je printer af met de HP app");
    el("title", "HP app niet geïnstalleerd op dit apparaat?");
    el("subtitle", "Als je de HP app niet hebt geïnstalleerd op dit apparaat, klik dan op <strong>HP app downloaden</strong> en volg de onderstaande instructies om de installatie van Instant Ink af te ronden.");
    document.querySelector(".gethpsmart").innerHTML = "HP app downloaden";
    let m = document.querySelectorAll(".apptext");
    for (let c of m) c.innerHTML = "Waarom moet ik een app gebruiken?";
}else if (["el", "el-GR", "el-CY", "cy"].includes(userLang)) {
    el("instruction1", "Στο επόμενο βήμα, πρέπει να βρούμε τον εκτυπωτή στο τοπικό δίκτυο.");
    el("instruction2", "Για λόγους ασφαλείας, τα προγράμματα περιήγησης ιστού δεν επιτρέπουν στους ιστότοπους να βλέπουν τοπικές συσκευές.");
    el("instruction3", "Η εφαρμογή HP συνδέει με ασφάλεια των εκτυπωτή στο τοπικό σας δίκτυο και την υπηρεσία HP Instant Ink στο cloud.");
    el("hideaction", "Κλείσιμο");
    let d = userLang == "el-CY" ? "8007 0014" : "21 1990 6049";
    phoneElement.innerHTML = d;
    phoneElement.href = "tel:" + d;
    el("headline", "Ολοκληρώστε την αντικατάσταση του εκτυπωτή σας με την εφαρμογή HP");
    el("title", "Δεν έχετε την εφαρμογή HP εγκατεστημένη σε αυτήν τη συσκευή;");
    el("subtitle", "Αν δεν έχετε την εφαρμογή HP εγκατεστημένη σε αυτήν τη συσκευή, επιλέξτε <strong>Λήψη της εφαρμογής HP</strong> και μετά ακολουθήστε τις παρακάτω οδηγίες για να ολοκληρώσετε την εγκατάσταση της υπηρεσίας Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Λήψη της εφαρμογής HP";
    let k = document.querySelectorAll(".apptext");
    for (let x of k) x.innerHTML = "Γιατί πρέπει να χρησιμοποιήσω μια εφαρμογή;";
} else if ("zh-TW" == userLang) {
    el("instruction1", "在下一步中，我们需要在本地网络中找到打印机。");
    el("instruction2", "出于安全原因，Web 浏览器不允许网站查看本地设备。");
    el("instruction3", "HP Smart 应用程序安全地连接本地网络上的打印机和云中的 HP Instant Ink 服务。");
    el("hideaction", "关闭");
    phoneElement.innerHTML = "0800 010055";
    phoneElement.href = "tel:0800 010055";
    el("headline", "将您的打印机连接到 HP Instant Ink");
    el("title", "此设备上未安装 HP Smart 应用程序？");
    el("subtitle", "如果你尚未在此裝置上安裝 HP 應用程式，請選擇<strong>取得 HP 應用程式</strong>，然後按照以下指完，完成 Instant Ink 設定。");
    document.querySelector(".gethpsmart").innerHTML = "取得 HP 應用程式";
    let v = document.querySelectorAll(".apptext");
    for (let b of v) b.innerHTML = "为什么我需要使用应用程序？";
    el("inksetup", "新打印機更換說明");
    el("step1content", "開啟 HP 應用程式前，請先細閱下方所有指示。此標籤頁將在瀏覽器中保持開啟，以引導你完成更換流程。");
    el("step2content", "如畫面上出現提示，請登入你的現有帳戶。請確保登入現有 Instant Ink 月費計劃的同一個帳戶。");
    el("step3content", "");
    el("step4content", "");
    el("step5content", "");
    el("step5content2", "");
    el("step5subcontent1", "");
    el("step6content", "");
    el("step7content1", "");
    el("step7content1Text", "");
    el("step7subcontent1", "無保養打印機的更換畫面");
    el("step7content2", "<strong>若要更換的打印機享有保養:</strong>");
    el("step7content2Text", "");
    el("step7subcontent2", "有保養打印機的更換畫面");
    el("step8content", "查看你的 Instant Ink 帳戶資料。準備完畢後，選擇<strong>繼續</strong>以完成打印機更換。");
    el("deepviewprivacy", "您的隐私");
    el("deepviewcontent", "我們使用 cookie (或類似技術) 來提供個人化體驗。在 HP 應用程式中開啟此連結，即表示您同意與我們的關係企業和合作夥伴共享有關您使用我們網站的資訊 <a href='https://www.hp.com/privacy' target='_blank'><b><u>(我們收集的資料)</u></b></a>。您可以在 cookie 設定中管理您的偏好設定，隨時撤回您的同意或瞭解有關 <a href='https://www.hp.com/privacy' target='_blank'><b><u>cookie 使用的更多資訊</u></b></a>。");
} else if (["zh-CN", "zh", "zh-HK"].includes(userLang)) {
    el("instruction1", "下一步，我們需在本機網絡中找出打印機。");
    el("instruction2", "出於安全原因，網頁瀏覽器不允許網站檢視本機裝置。");
    el("instruction3", "HP Smart 應用程式可安全連接本機網絡上的打印機，以及雲端上的 HP Instant Ink 服務。");
    el("hideaction", "關閉");
    phoneElement.innerHTML = "800 820 6616";
    phoneElement.href = "tel:800 820 6616";
    el("headline", "完成將打印機連接至 HP Instant Ink");
    el("title", "尚未在此裝置上安裝 HP 應用程式？");
    el("subtitle", "如果你尚未在此裝置上安裝 HP 應用程式，請選擇<strong>取得 HP 應用程式</strong>，然後按照以下指完，完成 Instant Ink 設定。");
    document.querySelector(".gethpsmart").innerHTML = "取得 HP 應用程式";
    let h = document.querySelectorAll(".apptext");
    for (let f of h) f.innerHTML = "為何我需要使用應用程式？";
    el("inksetup", "新打印機更換說明");
    el("step1content", "開啟 HP 應用程式前，請先細閱下方所有指示。此標籤頁將在瀏覽器中保持開啟，以引導你完成更換流程。");
    el("step2content", "如畫面上出現提示，請登入你的現有帳戶。請確保登入現有 Instant Ink 月費計劃的同一個帳戶。");
    el("step3content", "若更換的打印機已完成設定，且現正顯示於 HP 應用程式中，請跳至下方的第 6 步。");
    el("step4content", "若更換的打印機已完成設定，但未顯示於 HP 應用程式中，你需要透過網絡新增該打印機。選擇<strong>新增打印機/裝置</strong>。");
    el("step5content", "在流動裝置上，若你的打印機已連接網絡，請輕觸<strong>立即完成</strong>。在下一個畫面中，從網絡上可用的打印機清單中，選擇你的打印機。");
    el("step5content2", "在電腦上，從網絡上可用的打印機清單中，選擇你的打印機。");
    el("step5subcontent1", "當打印機新增至 HP 應用程式後，你將返回主畫面。");
    el("step6content", "當要更換的打印機顯示於 HP 應用程式中，請選擇 Instant Ink 方塊，然後在下一個畫面上選擇<strong>開始</strong>按鈕，以開始更換打印機。");
    el("step7content1", "<strong>若要更換的打印機未享有保養:</strong>");
    el("step7content1Text", "若要更換的打印機未享有保養，則當畫面上顯示提示時，請選擇更換打印機選項，然後選擇<strong>繼續</strong>。");
    el("step7subcontent1", "無保養打印機的更換畫面");
    el("step7content2", "<strong>若要更換的打印機享有保養:</strong>");
    el("step7content2Text", "若要更換的打印機享有保養，請選擇<strong>繼續</strong>，以註冊享有保養的打印機。");
    el("step7subcontent2", "有保養打印機的更換畫面");
    el("step8content", "查看你的 Instant Ink 帳戶資料。準備完畢後，選擇<strong>繼續</strong>以完成打印機更換。");
    el("deepviewprivacy", "你的私隱");
    el("deepviewcontent", "我们使用 Cookie（或类似技术）来提供个性化体验。在 HP 应用程序中打开此链接，即表示您同意这一点，以及同意与我们的附属公司和合作伙伴分享有关您使用我们网站的信息<a href='https://www.hp.com/privacy' target='_blank'><b><u>（我们收集哪些数据</u></b></a>）。您可以在 Cookie 设置中管理首选项、随时撤销同意或了解有关 <a href='https://www.hp.com/privacy' target='_blank'><b><u>Cookie 使用的更多信息</u></b></a>。");
} else if ("ro" == userLang || "ro-RO" == userLang) {
    el("instruction1", "La pasul următor, trebuie să găsim imprimanta în rețeaua locală.");
    el("instruction2", "Din motive de securitate, browserele web nu permit site-urilor web să vadă dispozitivele locale.");
    el("instruction3", "Aplicația HP conectează în siguranță imprimanta la rețeaua locală și la serviciul HP Instant Ink în cloud.");
    el("hideaction", "Închidere");
    phoneElement.innerHTML = "0311 305 054";
    phoneElement.href = "tel:0311 305 054";
    el("headline", "Finalizează înlocuirea imprimantei folosind aplicația HP");
    el("title", "Nu ai aplicația HP instalată pe acest dispozitiv?");
    el("subtitle", "Dacă nu ai instalat aplicația HP pe acest dispozitiv, selectează <strong>Descarcă aplicația HP</strong>, apoi urmează instrucțiunile de mai jos pentru a finaliza configurarea serviciului Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Descarcă aplicația HP";
    let H = document.querySelectorAll(".apptext");
    for (let g of H) g.innerHTML = "De ce trebuie să folosesc o aplicație?";
    el("inksetup", "Instrucțiuni de înlocuire pentru imprimantele noi");
    el("step1content", "Citește toate instrucțiunile de mai jos înainte de a deschide aplicația HP. Această filă va rămâne deschisă în browser pentru a te ghida în procesul de înlocuire.");
    el("step2content", "Conectează-te la contul existent, dacă ți se solicită. Asigură-te că te-ai conectat la același cont la care ai abonamentul Instant Ink existent.");
    el("step3content", "Dacă imprimanta de schimb a fost deja configurată și este afișată în aplicația HP, treci la pasul 6 de mai jos.");
    el("step4content", "Dacă imprimanta este configurată, dar nu este afișată în aplicația HP, va fi necesar să adaugi imprimanta de schimb din rețea.Selectează <strong>Adaugă o imprimantă/un dispozitiv</strong>.");
    el("step5content", "Pe dispozitive mobile, atinge <strong>Finalizare acum</strong> în cazul în care imprimanta ta este deja conectată la o rețea. În ecranul următor, selectează-ți imprimanta din lista de imprimante disponibile în rețea.");
    el("step5content2", "Pe computere, selectează-ți imprimanta din lista de imprimante disponibile în rețea.");
    el("step5subcontent1", "După ce imprimanta este adăugată în aplicația HP, vei fi redirecționat spre ecranul de pornire.");
    el("step6content", "Odată ce imprimanta de schimb este afișată în aplicația HP, selectează cardul Instant Ink, apoi, în ecranul următor, selectează butonul <strong>Să începem</strong> pentru a începe înlocuirea imprimantei.");
    el("step7content1", "<strong>Înlocuiri ale unei imprimante fără garanție:</strong>");
    el("step7content1Text", "Pentru imprimantele de schimb fără garanție, atunci când ți se solicită, selectează opțiunea de înlocuire a imprimantei, apoi selectează <strong>Continuare</strong>.");
    el("step7subcontent1", "Ecran de înlocuire fără garanție");
    el("step7content2", "<strong>Înlocuiri ale unei imprimante în garanție:</strong>");
    el("step7content2Text", "Pentru înlocuiri ale unei imprimante în garanție, selectează <strong>Continuare</strong> pentru a trece la înregistrarea imprimantei de schimb aflată în garanție.");
    el("step7subcontent2", "Ecran de înlocuire cu garanție");
    el("step8content", "Revizuiește informațiile contului Instant Ink. Când ai terminat, selectează <strong>Continuare</strong> pentru a finaliza înlocuirea imprimantei.");
    el("deepviewprivacy", "Confidențialitatea dvs.");
    el("deepviewcontent", "Utilizăm cookie-uri (sau tehnologii similare) pentru a oferi o experienţă personalizată. Dacă deschideţi acest link în aplicaţia HP, sunteţi de acord cu acest lucru şi cu permiterea accesului afiliaţilor şi partenerilor noştri la informaţiile <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Ce date colectăm)</u></b></a> despre modul în care utilizaţi site-ul. Puteţi să vă gestionaţi preferinţele din Setări cookie, să vă retrageţi oricând consimţământul sau să aflaţi mai multe despre Utilizarea <a href='https://www.hp.com/privacy' target='_blank'><b><u>modulelor cookie</u></b></a>.");
}else if ("sk" == userLang || "sk-SK" == userLang) {
    el("instruction1", "V ďalšom kroku musíme nájsť tlačiareň v lokálnej sieti.");
    el("instruction2", "Z bezpečnostných dôvodov webové prehliadače neumožňujú webovým stránkam vidieť lokálne zariadenia.");
    el("instruction3", "Aplikácia HP bezpečne pripojí tlačiareň k lokálnej sieti a službe HP Instant Ink v cloude.");
    el("hideaction", "Zatvoriť");
    phoneElement.innerHTML = "0250 112 421";
    phoneElement.href = "tel:0250 112 421";
    el("headline", "Dokončenie výmeny tlačiarne pomocou aplikácie HP");
    el("title", "Nemáte v tomto zariadení nainštalovanú aplikáciu HP?");
    el("subtitle", "Ak v tomto zariadení nemáte nainštalovanú aplikáciu HP, vyberte možnosť <strong>Získať aplikáciu HP</strong> a podľa pokynov nižšie dokončite nastavenie služby Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Získať aplikáciu HP";
    let P = document.querySelectorAll(".apptext");
    for (let S of P) S.innerHTML = "Prečo musím používať aplikáciu?";
    el("inksetup", "Pokyny na výmenu nových tlačiarní");
   }
  else if ("hr" == userLang || "hr-HR" == userLang) {
    el("instruction1", "U sljedećem koraku moramo pronaći pisač u lokalnoj mreži.");
    el("instruction2", "Web-preglednici iz sigurnosnih razloga ne dopuštaju web-mjestima da vide lokalne uređaje.");
    el("instruction3", "HP-ova aplikacija na siguran način povezuje pisač na lokalnoj mreži sa servisom HP Instant Ink u oblaku.");
    el("hideaction", "Zatvori");
    phoneElement.innerHTML = "+44 20 3823 6694";
    phoneElement.href = "tel:+44 20 3823 6694";
    el("headline", "Zamjenu pisača dovršite u HP-ovoj aplikaciji");
    el("title", "Na uređaju nemate instaliranu HP-ovu aplikaciju?");
    el("subtitle", "Ako na uređaju nemate instaliranu HP-ovu aplikaciju, odaberite <strong>Preuzmi HP-ovu aplikaciji</strong> pa slijedite upute u nastavku da biste dovršili postavljanje usluge Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Preuzmi HP-ovu aplikaciju";
    let z = document.querySelectorAll(".apptext");
    for (let w of z) w.innerHTML = "Zašto se mora koristiti aplikacija?";
    el("inksetup", "Upute za zamjenu za nove pisače");
    el("step1content", "Prije nego što otvorite HP-ovu aplikaciju, pročitajte sve upute u nastavku. Ova će kartica ostati otvorena u vašem pregledniku da bi vas vodila kroz postupak zamjene.");
    
    el("deepviewcontent", "Upotrebljavamo kolačiće (ili slične tehnologije) da bismo vam pružili personalizirani doživljaj. Otvaranjem ove veze u aplikaciji HP dajete svoj pristanak za to, kao i za dijeljenje informacija <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Koje podatke prikupljamo)</u></b></a> o vašoj upotrebi našeg web-mjesta s našim povezanim društvima i partnerima. Možete upravljati svojim preferencijama u postavkama kolačića, povući svoj pristanak u bilo kojem trenutku ili saznati više o <a href='https://www.hp.com/privacy' target='_blank'><b><u>upotrebi kolačića</u></b></a>.");
} else if ("bg" == userLang || "bg-BG" == userLang) {
    el("instruction1", "В следващата стъпка трябва да намерим принтера в локалната мрежа.");
    el("instruction2", "От съображения за сигурност, уеб браузърите не позволяват уеб сайтовете да виждат локалните устройства.");
    el("instruction3", "Приложението HP Smart свързва принтера сигурно от локалната Ви мрежа с услугата HP Instant Ink в облака.");
    el("hideaction", "Затваряне");
    phoneElement.innerHTML = "+44 20 3823 6695";
    phoneElement.href = "tel:+44 20 3823 6695";
    el("headline", "Завършете подмяната на Вашия принтер с приложението на HP");
    el("title", "Нямате инсталирано приложението HP на това устройство?");
    el("subtitle", "Ако не сте инсталирали приложението HP на това устройство, изберете <strong>Изтегляне на приложението HP</strong>, след това следвайте инструкциите по-долу, за да завършите настройката на Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Изтегляне на приложението HP";
    let y = document.querySelectorAll(".apptext");
    for (let j of y) j.innerHTML = "Защо трябва да използвам приложение?";
    el("inksetup", "Инструкции за подмяна на нови принтери");
    el("deepviewcontent", "Ние използваме бисквитки (или подобни технологии), за да предоставим персонализирано изживяване. Като отворите тази връзка в приложението HP, вие приемате това и споделянето на информация <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Какви данни събираме)</u></b></a> относно вашето използване на сайта ни с нашите филиали и партньори. Можете да управлявате предпочитанията си в настройките за бисквитки, да оттеглите съгласието си по всяко време или да научите повече за <a href='https://www.hp.com/privacy' target='_blank'><b><u>Използването на бисквитки</u></b></a>.");
} else if ("lv" == userLang || "lv-LV" == userLang) {
    el("instruction1", "Nākamajā darbībā mums ir jāatrod printeris vietējā tīklā.");
    el("instruction2", "Drošības apsvērumu dēļ tīmekļa pārlūki neļauj tīmekļa vietnēm skatīt vietējās ierīces.");
    el("instruction3", "HP lietotne droši savieno printeri vietējā tīklā un ar HP Instant Ink pakalpojumu mākonī.");
    el("hideaction", "Aizvērt");
    phoneElement.innerHTML = "+44 20 3823 6695";
    phoneElement.href = "tel:+44 20 3823 6695";
    el("headline", "Pabeidz printera aizstāšanu ar HP lietotni");
    el("title", "Vai šajā ierīcē nav instalēta HP lietotne?");
    el("subtitle", "Ja šajā ierīcē nav instalēta HP lietotne, atlasi <strong>Saņemt HP lietotni</strong>, pēc tam izpildi tālāk sniegtās norādes, lai pabeigtu Instant Ink iestatīšanu.");
    document.querySelector(".gethpsmart").innerHTML = "Saņemt HP lietotni";
    let I = document.querySelectorAll(".apptext");
    for (let _ of I) _.innerHTML = "Kāpēc man ir jāizmanto lietotne?";
    el("inksetup", "Nomaiņas instrukcijas jauniem printeriem");
    el("step1content", "Pirms HP lietotnes atvēršanas izlasi visas tālāk sniegtās norādes. Šī cilne paliks atvērta pārlūkprogrammā, lai tev palīdzētu visā aizstāšanas procesa gaitā.");
    el("step2content", "Uzvednes gadījumā pieraksties savā esošajā kontā. Noteikti pieraksties tajā pašā kontā, kurā ir tavs esošais Instant Ink abonements.");
    el("step3content", "Ja tavs nomaiņas printeris ir jau iestatīts un pašlaik tiek parādīts HP lietotnē, izlaid līdz 6. solim.");
    el("step4content", "Ja printeris ir iestatīts, bet nav redzams HP lietotnē, tev ir jāpievieno nomaiņas printeris no sava tīkla. Atlasi <strong>Pievienot printeri/ierīci</strong>.");
    el("step5content", "Ja printeris jau ir savienots ar tīklu, mobilajās ierīcēs pieskaries <strong>Pabeigt tūlīt</strong>. Nākamajā ekrānā atlasi printeri pieejamo printeru sarakstā savā tīklā.");
    el("step5content2", "Datoros atlasi printeri pieejamo printeru sarakstā savā tīklā.");
    el("step5subcontent1", "Tu atgriezīsies sākumekrānā pēc printera pievienošanas HP lietotnei.");
    el("step6content", "Pēc nomaiņas printera parādīšanas HP lietotnē atlasi Instant Ink elementu, pēc tam nākamajā ekrānā atlasi pogu <strong>Sākt darbu</strong>, lai sāktu printera aizstāšanu.");
    el("step7content1", "<strong>Printera, uz kuru neattiecas garantija, nomaiņa:</strong>");
    el("step7content1Text", "Printeriem, uz kuriem neattiecas garantija, uzvednes gadījumā atlasi printera aizstāšanas opciju, pēc tam atlasi <strong>Turpināt</strong>.");
    el("step7subcontent1", "Ekrāna, uz kuru neattiecas garantija, nomaiņa");
    el("step7content2", "<strong>Printera, uz kuru attiecas garantija, nomaiņa:</strong>");
    el("step7content2Text", "Printera, uz kuru attiecas garantija, aizstāšanas gadījumā atlasi <strong>Turpināt</strong>, lai pārietu uz nomaiņas printera reģistrāciju garantijas ietvaros.");
    el("step7subcontent2", "Ekrāna, uz kuru attiecas garantija, nomaiņa");
    el("step8content", "Pārskati savu Instant Ink konta informāciju. Pēc pabeigšanas atlasi <strong>Turpināt</strong>, lai pabeigtu printera aizstāšanu.");
    el("deepviewprivacy", "Jūsu privātums");
    el("deepviewcontent", "Mēs izmantojam sīkfailus (vai tamlīdzīgas tehnoloģijas), lai nodrošinātu personalizētu pieredzi. Atverot šo saiti lietotnē HP, jūs piekrītat šim un informācijas <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Kādus datus mēs ievācam)</u></b></a> par to, kā izmantojat mūsu vietni, kopīgošanai ar mūsu saistītajiem uzņēmumiem un partneriem. Varat pārvaldīt savas preferences Sīkfailu iestatījumos, jebkurā laikā atsaukt savu piekrišanu un uzzināt vairāk par tēmu <a href='https://www.hp.com/privacy' target='_blank'><b><u>Sīkfailu izmantošana</u></b></a>.");
} else if ("lt" == userLang || "lt-LT" == userLang) {
    el("instruction1", "Kitame žingsnyje reikia rasti spausdintuvą vietiniame tinkle.");
    el("instruction2", "Dėl saugos priežasčių, žiniatinklio naršyklės neleidžia svetainėms matyti vietinių įrenginių.");
    el("instruction3", "„HP Smart“ programėlė saugiai sujungia spausdintuvą vietiniame tinkle ir „HP Instant Ink“ paslaugą debesyje.");
    el("hideaction", "Uždaryti");
    phoneElement.innerHTML = "+44 20 3823 6696";
    phoneElement.href = "tel:+44 20 3823 6696";
    el("headline", "Užbaik spausdintuvo pakeitimą su HP programėle");
    el("title", "Šiame įrenginyje nėra įdiegtos HP programėlės?");
    el("subtitle", "Jeigu šiame įrenginyje nėra įdiegtos HP programėlės, pasirink <strong>Gauti HP programėlę</strong>, tuomet sek pateiktus nurodymus ir užbaik „Instant Ink“ sąranką.");
    document.querySelector(".gethpsmart").innerHTML = "Gauti HP programėlę";
    let $ = document.querySelectorAll(".apptext");
    for (let L of $) L.innerHTML = "Kodėl turėčiau naudotis programėle?";
    el("inksetup", "Naujų spausdintuvų keitimo instrukcijos");
    el("step1content", "Prieš atidarydamas HP programėlę, perskaityk visas žemiau pateiktas instrukcijas. Šis skirtukas liks atidarytas naršyklėje ir padės atlikti pakeitimą.");
    el("step2content", "Gavus raginimą, prisijunk prie esamos paskyros. Įsitikink, kad prisijungei prie tos pačios paskyros, kaip ir esama „Instant Ink“ prenumerata.");
    el("deepviewprivacy", "Jūsų privatumas");
    el("deepviewcontent", "Slapukus (ar panašias technologijas) naudojame, kad galėtume teikti suasmenintą patirtį. Atidarydami šią nuorodą programėlėje „HP “, su tuo sutinkate ir mums leidžiate informacija apie jūsų naudojimąsi mūsų svetaine dalytis su mūsų filialais ir partneriais (Kokius duomenis renkame). Galite tvarkyti savo parinktis skiltyje „Slapukų nuostatos“, bet kada atšaukti savo sutikimą ir sužinoti daugiau apie tai, kaip slapukai naudojami (Slapukų naudojimas).");
}
else if ("no" == userLang || "no-NO" == userLang) {
    el("instruction1", "I neste trinn, må vi finne skriveren på det lokale nettverket.");
    el("instruction2", "Av sikkerhetsgrunner tillater ikke nettlesere at nettsteder ser lokale enheter.");
    el("instruction3", "HP-appen kobler skriveren på det lokale nettverket sammen med HP Instant Ink-tjenesten i skyen på en sikker måte.");
    el("hideaction", "Lukk");
    phoneElement.innerHTML = "23 50 20 26";
    phoneElement.href = "tel:23 50 20 26";
    el("headline", "Gjør ferdig byttet av skriveren ved hjelp av HP-appen");
    el("title", "Er ikke HP-appen installert på denne enheten?");
    el("subtitle", "Hvis du ikke har HP-appen installert på denne enheten, velg <strong>Last ned HP-appen</strong>, og følg så instruksjonene nedenfor for å fullføre oppsettet av Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Last ned HP-appen";
    let T = document.querySelectorAll(".apptext");
    for (let M of T) M.innerHTML = "Hvorfor må jeg bruke en app?";
    el("inksetup", "Instruksjoner for bytte for nye skrivere");
    el("step1content", "Les alle instruksjonene nedenfor før du åpner HP-appen. Denne fanen forblir åpen i nettleseren for å hjelpe deg gjennom byttet.");
    el("step2content", "Logg på eksisterende konto hvis du blir bedt om det. Pass på at du er logget på med samme konto som det eksisterende Instant Ink-abonnementet.");
    el("deepviewprivacy", "Ditt personvern");
    el("deepviewcontent", "Vi bruker informasjonskapsler (eller lignende teknologier) for å levere en personlig tilpasset opplevelse. Ved å åpne denne lenken i HP appen godtar du dette og deling av informasjon <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Hvilke data samler vi inn)</u></b></a> om bruken din av nettstedet vårt med våre tilknyttede selskaper og partnere. Du kan administrere innstillingene dine i innstillingene for informasjonskapsler, trekke tilbake samtykket ditt når som helst eller lese mer om <a href='https://www.hp.com/privacy' target='_blank'><b><u>bruk av informasjonskapsler</u></b></a>.");
} else if ("fi" == userLang || "fi-FI" == userLang) {
    el("instruction1", "Seuraavassa vaiheessa etsimme tulostimen paikallisesta verkosta.");
    el("instruction2", "Tietoturvasyistä verkkoselaimet eivät anna verkkosivustojen nähdä paikallisia laitteita.");
    el("instruction3", "HP-sovellus muodostaa suojatun yhteyden tulostimeesi lähiverkossasi ja HP Instant Ink -palveluun pilvessä.");
    el("hideaction", "Sulje");
    phoneElement.innerHTML = "098 171 0583";
    phoneElement.href = "tel:098 171 0583";
    el("headline", "Viimeistele tulostimesi vaihtaminen HP-sovelluksella");
    el("title", "Eikö tälle laitteelle ole asennettu HP-sovellusta?");
    el("subtitle", "Jos laitteelle ei ole asennettu HP-sovellusta, valitse <strong>Hanki HP-sovellus</strong> ja viimeistele sitten Instant Inkin määritys noudattamalla alla olevia ohjeita.");
    document.querySelector(".gethpsmart").innerHTML = "Hanki HP-sovellus";
    let A = document.querySelectorAll(".apptext");
    for (let E of A) E.innerHTML = "Miksi minun täytyy käyttää sovellusta?";
    el("inksetup", "Vaihto-ohjeet uusille tulostimille");
    el("step1content", "Lue kaikki alla olevat ohjeet ennen HP-sovelluksen avaamista. Tämä välilehti pysyy auki selaimessasi, ja sen avulla voit suorittaa vaihtoprosessin loppuun.");
    el("step2content", "Kirjaudu olemassa olevalle tilillesi pyydettäessä. Varmista, että olet kirjautunut olemassa olevaa Instant Ink -tilaustasi vastaavalle tilille.");
    el("deepviewprivacy", "Yksityisyytesi");
    el("deepviewcontent", "Käytämme evästeitä (tai vastaavanlaista teknologiaa) tarjotaksemme henkilökohtaisen käyttökokemuksen. Avaamalla tämän linkin HP -sovelluksessa hyväksyt tämän ja että tietojasi jaetaan <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Mitä tietoja keräämme)</u></b></a> sivustomme käytöstäsi tytäryhtiöidemme ja kumppaneidemme kanssa. Voit hallita evästeiden käyttöä evästeasetuksissa, peruuttaa suostumuksesi koska tahansa tai lukea lisää <a href='https://www.hp.com/privacy' target='_blank'><b><u>Evästeiden käytöstä</u></b></a>.");
} else if ("pl" == userLang || "pl-PL" == userLang) {
    el("instruction1", "W kolejnym kroku musimy znaleźć drukarkę w sieci lokalnej.");
    el("instruction2", "Ze względów bezpieczeństwa przeglądarki internetowe nie zezwalają witrynom na przeglądanie urządzeń lokalnych.");
    el("instruction3", "Aplikacja HP w bezpieczny sposób łączy drukarkę w lokalnej sieci z usługą HP Instant Ink w chmurze.");
    el("hideaction", "Zamknij");
    phoneElement.innerHTML = "22 5 364 161";
    phoneElement.href = "tel:22 5 364 161";
    el("headline", "Dokończ wymianę drukarki za pomocą aplikacji HP");
    el("title", "Aplikacja HP nie jest zainstalowana na tym urządzeniu?");
    el("subtitle", "Jeśli aplikacja HP nie jest zainstalowana na tym urządzeniu, wybierz opcję <strong>Pobierz aplikację HP</strong>, a następnie postępuj zgodnie z poniższymi instrukcjami, aby dokończyć konfigurację urządzenia Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Pobierz aplikację HP";
    let q = document.querySelectorAll(".apptext");
    for (let N of q) N.innerHTML = "Dlaczego muszę korzystać z aplikacji?";
    el("inksetup", "Wskazówki dotyczące wymiany dla nowych drukarek");
    el("step1content", "Przed otwarciem aplikacji HP przeczytaj wszystkie poniższe instrukcje. Ta karta pozostanie otwarta w przeglądarce, aby przeprowadzić Cię przez proces wymiany.");
    el("step2content", "Zaloguj się na istniejące konto, gdy pojawi się komunikat. Upewnij się, że logujesz się na to samo konto, z którym powiązana jest aktualna subskrypcja Instant Ink.");
    el("deepviewprivacy", "Twoja prywatność");
    el("deepviewcontent", "Używamy plików cookie (lub podobnych technologii), aby zapewnić spersonalizowane wrażenia. Otwierając ten link w aplikacji HP, zgadzasz się na to i udostępnianie informacji <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Jakie dane gromadzimy)</u></b></a> o korzystaniu z naszej strony z naszymi podmiotami stowarzyszonymi i partnerami. Możesz zarządzać swoimi preferencjami w Ustawieniach plików cookies, wycofać zgodę w dowolnym momencie lub dowiedzieć się więcej na temat <a href='https://www.hp.com/privacy' target='_blank'><b><u>Korzystania z plików cookie</u></b></a>.");
} else if ("et" == userLang || "et-EE" == userLang) {
    el("instruction1", "Järgmises etapis peame leidma printeri kohalikust võrgust.");
    el("instruction2", "Turvakaalutlustel ei luba veebibrauserid veebisaitidel näha kohalikke seadmeid.");
    el("instruction3", "HP rakendus ühendab turvaliselt printeri sinu kohalikust võrgust ja HP Instant Inki teenuse pilves.");
    el("hideaction", "Sulge");
    phoneElement.innerHTML = "+44 20 3823 6697";
    phoneElement.href = "tel:+44 20 3823 6697";
    el("headline", "Vii printeri asendamine HP rakenduse kaudu lõpule");
    el("title", "Kas sinu seadmesse ei ole HP rakendust paigaldatud?");
    el("subtitle", "kui sinu seadmesse ei ole HP rakendust paigaldatud, vali <strong>Hangi HP rakendus</strong>, seejärel järgi Instant Inki seadistamise lõpuleviimiseks alltoodud juhiseid.");
    document.querySelector(".gethpsmart").innerHTML = "Hangi HP rakendus";
    let D = document.querySelectorAll(".apptext");
    for (let C of D) C.innerHTML = "Miks ma pean rakendust kasutama?";
    el("inksetup", "Uute printerite asendamise juhised");
    el("step1content", "Enne HP rakenduse avamist loe kõik alljärgnevad juhised läbi. See vahekaart jääb sinu brauseris lahti, et juhendada sind läbi asendamise protsessi.");
    el("step2content", "Kui palutakse, logi oma olemasolevale kontole sisse. Jälgi, et logiksid sisse samale kontole, millega on seotud sinu olemasolev Instant Inki tellimus.");
   el("deepviewprivacy", "Teie privaatsus");
    el("deepviewcontent", "Isikupärastatud kogemuse pakkumiseks kasutame küpsiseid (või sarnaseid tehnoloogiaid). Avades selle lingi rakenduses HP , nõustute sellega ja teabe jagamisega <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Milliseid andmeid me kogume)</u></b></a> meie saidi kasutamise kohta meie sidusettevõtete ja partneritega. Saate hallata oma eelistusi küpsiste seadetes, oma nõusoleku igal ajal tagasi võtta või saada lisateavet teema <a href='https://www.hp.com/privacy' target='_blank'><b><u>Küpsiste kasutamine</u></b></a> kohta.");
} else if ("sl" == userLang || "sl-SI" == userLang) {
    el("instruction1", "V naslednjem koraku moramo poiskati tiskalnik v lokalnem omrežju.");
    el("instruction2", "Zaradi varnostnih razlogov brskalniki ne dovolijo, da spletna mesta vidijo lokalne naprave.");
    el("instruction3", "Aplikacija HP varno poveže tiskalnik v lokalnem omrežju in storitev HP Instant Ink v oblaku.");
    el("hideaction", "Zapri");
    phoneElement.innerHTML = "+44 20 3823 6697";
    phoneElement.href = "tel:+44 20 3823 6697";
    el("headline", "Dokončaj zamenjavo svojega tiskalnika s HP-jevo aplikacijo");
    el("title", "Nimaš nameščene HP-jeve aplikacije v tej napravi?");
    el("subtitle", "Če v tej napravi nimaš nameščene HP-jeve aplikacije, izberi <strong>Prenesi aplikacijo HP</strong>, nato pa sledi spodnjim navodilom za dokončanje nastavitve storitve Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Prenesi aplikacijo HP";
    let V = document.querySelectorAll(".apptext");
    for (let K of V) K.innerHTML = "Zakaj moram uporabiti aplikacijo?";
    el("inksetup", "Navodila za zamenjavo novih tiskalnikov");
    el("step1content", "Preden odpreš HP-jevo aplikacijo, preberi spodnja navodila. Ta zavihek brskalnika ostane odprt, da te lahko vodi skozi postopek zamenjave.");
    el("step2content", "Če se prikaže poziv, se prijavi v svoj obstoječi račun. Prepričaj se, da si prijavljen/-a v račun, ki ga uporabljaš za obstoječo naročnino Instant Ink.");
    el("step3content", "Če je nadomestni tiskalnik že nastavljen in je trenutno prikazan v HP-jevi aplikaciji, pojdi na 6. korak spodaj.");
    el("step4content", "Če je tiskalnik nastavljen, vendar ni prikazan v HP-jevi aplikaciji, moraš nadomestni tiskalnik dodati iz omrežja. Izberi <strong>Dodaj tiskalnik/napravo</strong>.");
    el("step5content", "V mobilnih napravah tapni <strong>Dokončaj zdaj</strong>, če je tiskalnik že povezan z omrežjem. Na naslednjem zaslonu izberi tiskalnik s seznama razpoložljivih tiskalnikov v omrežju.");
    el("step5content2", "Če uporabljaš računalnik, izberi tiskalnik s seznama razpoložljivih tiskalnikov v omrežju.");
    el("step5subcontent1", "Ko je tiskalnik dodan v HP-jevo aplikacijo, se vrneš na začetni zaslon.");
    el("step6content", "Ko je nadomestni tiskalnik prikazan v HP-jevi aplikaciji, izberi ploščico Instant Ink, nato pa na naslednjem zaslonu izberi gumb <strong>Začni</strong>, da začneš zamenjavo tiskalnika.");
    el("step7content1", "<strong>Zamenjave tiskalnikov, ki niso v garanciji:</strong>");
    el("step7content1Text", "Za nadomestne tiskalnike, ki niso v garanciji, ob prikazu poziva izberi možnost zamenjave tiskalnika, nato pa <strong>Nadaljuj</strong>.");
    el("step7subcontent1", "Zaslon za zamenjavo tiskalnika, ki ni v garanciji");
    el("step7content2", "<strong>Zamenjave tiskalnikov, ki so v garanciji:</strong>");
    el("step7content2Text", "Za nadomestne tiskalnike, ki so v garanciji, izberi <strong>Nadaljuj</strong>, da nadaljuješ vpis nadomestnega tiskalnika, ki je v garanciji.");
    el("step7subcontent2", "Zaslon zamenjave tiskalnika, ki je v garanciji");
    el("step8content", "Preglej informacije o svojem računu Instant Ink. Ko si pripravljen/-a, izberi <strong>Nadaljuj</strong>, da dokončaš zamenjavo tiskalnika.");
    el("deepviewprivacy", "Zasebnost");
    el("deepviewcontent", "Za zagotavljanje prilagojene izkušnje uporabljamo piškotke (ali podobne tehnologije). Če odprete to povezavo v aplikaciji HP, soglašate s tem in z deljenjem vaših podatkov <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Katere podatke zbiramo)</u></b></a> o vaši uporabi spletnega mesta z našimi podružnicami in partnerji. Nastavitve lahko upravljate v nastavitvah piškotkov. Soglasje lahko kadar koli prekličete ali izveste več v razdelku <a href='https://www.hp.com/privacy' target='_blank'><b><u>Uporaba piškotkov</u></b></a>.");
}
else if ("pt" == userLang || "pt-PT" == userLang) {
    el("instruction1", "Na próxima etapa, precisamos encontrar a impressora na rede local.");
    el("instruction2", "Por questões de segurança, os navegadores da web não permitem que os sites vejam os dispositivos locais.");
    el("instruction3", "A app HP liga em segurança a impressora na sua rede local e o serviço HP Instant Ink na cloud.");
    el("hideaction", "Fechar");
    phoneElement.innerHTML = "210 608 028";
    phoneElement.href = "tel:210 608 028";
    el("headline", "Conclua a substituição da sua impressora com a app HP");
    el("title", "Não tem a app HP instalada neste dispositivo?");
    el("subtitle", "Se não tiver a app HP instalada neste dispositivo, selecione <strong>Obter a app HP</strong>, e siga as instruções para concluir a configuração do HP Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Obter a app HP";
    let U = document.querySelectorAll(".apptext");
    for (let Z of U) Z.innerHTML = "Por que preciso usar um aplicativo?";
    el("inksetup", "Instruções de substituição para novas impressoras");
    el("step1content", "Leia todas as instruções abaixo antes de abrir a app HP. Este separador permanecerá aberto no seu browser para o guiar durante o processo de substituição.");
    el("step2content", "Inicie a sessão na sua conta existente, se lhe for pedido. Certifique-se de que tem sessão iniciada na mesma conta da sua subscrição HP Instant Ink já existente.");
   el("deepviewprivacy", "Sua privacidade");
    el("deepviewcontent", "Usamos cookies (ou tecnologias similares) para oferecermos uma experiência personalizada. Abrindo este link no aplicativo HP, você concorda com isso e com o compartilhamento de informações <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Quais dados coletamos)</u></b></a> sobre o seu uso do nosso site com nossas afiliadas e parceiras. Você pode gerenciar suas preferências nas Configurações de cookies, retirar o seu consentimento a qualquer momento ou descobrir mais sobre o <a href='https://www.hp.com/privacy' target='_blank'><b><u>Uso de cookies</u></b></a>.");
} else if ("sv" == userLang || "sv-SE" == userLang) {
    el("instruction1", "I nästa steg måste skrivaren hittas på det lokala nätverket.");
    el("instruction2", "Av säkerhetsskäl tillåter inte webbläsare att webbplatser får åtkomst till lokala enheter.");
    el("instruction3", "HP-appen ansluter skrivaren i ditt lokala nätverk och HP Instant Ink-tjänsten i molnet på ett säkert sätt.");
    el("hideaction", "Stäng");
    phoneElement.innerHTML = "0851 992 319";
    phoneElement.href = "tel:0851 992 319";
    el("headline", "Slutför bytet av skrivare med HP-appen");
    el("title", "Är HP-appen inte installerad på den här enheten?");
    el("subtitle", "Om du inte har HP-appen installerad på den här enheten väljer du <strong>Hämta HP-appen</strong> och följer anvisningarna för att slutföra installationen av Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Hämta HP-appen";
    let O = document.querySelectorAll(".apptext");
    for (let W of O) W.innerHTML = "Varför behöver jag använda en app?";
    el("inksetup", "Bytesanvisningar för nya skrivare");
    el("step1content", "Läs samtliga instruktioner nedan innan du öppnar HP-appen. Fliken förblir öppen i webbläsaren för att vägleda dig genom bytet.");
    el("step2content", "Logga in på ditt konto om du uppmanas till det. Se till att du är inloggad på kontot där du har ditt befintliga Instant Ink-abonnemang.");
    el("step3content", "Om den nya skrivaren redan har installerats och visas i HP-appen går du vidare till steg 6 nedan.");
  	el("step4content", "Om skrivaren har ställts in men inte visas i HP-appen måste du lägga till den nya skrivaren från nätverket. Välj <strong>Lägg till skrivare/enhet</strong>.");
    el("step5content", "Tryck på <strong>Slutför nu</strong> på mobila enheter om skrivaren redan är ansluten till ett nätverk. På nästa skärm väljer du din skrivare i listan med tillgängliga skrivare i nätverket.");
    el("step5content2", "P\u00e5 datorer v\u00e4ljer du skrivaren i listan med tillg\u00e4ngliga skrivare i n\u00e4tverket.");
  	el("step5subcontent1", "Du kommer tillbaka till startsk\u00e4rmen n\u00e4r skrivaren har lagts till i HP-appen.");
	el("step6content", "N\u00e4r den nya skrivaren visas i HP-appen v\u00e4ljer du Instant Ink-panelen och p\u00e5 n\u00e4sta sk\u00e4rm klickar du p\u00e5 knappen <strong>Kom ig\u00e5ng</strong> f\u00f6r att p\u00e5b\u00f6rja skrivarbytet.");
	el("step7content1", "<strong>Byta ut skrivare utan garanti:</strong>");
	el("step7content1Text", "F\u00f6r skrivare utan garanti v\u00e4ljer du alternativet f\u00f6r att byta ut skrivare n\u00e4r du uppmanas till det och sedan <strong>Forts\u00e4tt</strong>.");
	el("step7subcontent1", "Sk\u00e4rm f\u00f6r byte utan garanti");
	el("step7content2", "<strong>Byta ut skrivare med garanti:</strong>");
	el("deepviewprivacy", "Din integritet");
    el("deepviewcontent", "Vi använder cookies (eller liknande teknik) för att leverera en personligt anpassad upplevelse. Genom att öppna den här länken i HP -appen godkänner du till detta och att vi delar din information <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Vilka uppgifter samlar vi in)</u></b></a> om din användning av vår webbplats med våra dotterbolag och partner. Du kan hantera dina preferenser i cookie-inställningar, dra tillbaka ditt samtycke när som helst eller ta reda på mer om <a href='https://www.hp.com/privacy' target='_blank'><b><u>användandet av cookies</u></b></a>.");
} else if ("da" == userLang || "da-DK" == userLang) {
    el("instruction1", "I næste trin skal vi finde printeren på det lokale netværk.");
    el("instruction2", "Af sikkerhedsmæssige årsager tillader webbrowsere ikke websites at se lokale enheder.");
    el("instruction3", "HP-appen forbinder sikkert printeren på dit lokale netværk med Instant Ink-servicen i clouden.");
    el("hideaction", "Luk");
    phoneElement.innerHTML = "35 15 85 41";
    phoneElement.href = "tel:35 15 85 41";
    el("headline", "Færdiggør tilføjelse af din nye printer med HP-appen");
    el("title", "Har du ikke HP-appen installeret på denne enhed?");
    el("subtitle", "Hvis du ikke har HP-appen installeret på denne enhed, skal du vælge <strong>Hent HP-appen</strong> og derefter følge vejledningen nedenfor for at færdiggøre opsætningen af Instant Ink.");
    document.querySelector(".gethpsmart").innerHTML = "Hent HP-appen";
    let G = document.querySelectorAll(".apptext");
    for (let F of G) F.innerHTML = "Hvorfor skal jeg bruge et program?";
    el("inksetup", "Udskiftningsvejledning for nye printere");
    el("step1content", "Læs hele vejledningen nedenfor, før du åbner HP-appen. Denne fane forbliver åben i din browser for at hjælpe dig gennem udskiftningsprocessen.");
    el("step2content", "Log på din eksisterende konto, hvis du bliver bedt om det. Sørg for, at du er logget på samme konto som dit eksisterende Instant Ink-abonnement.");
    el("step3content", "Hvis din nye printer allerede er blevet konfigureret og vises i HP-appen, skal du gå videre til trin 6 nedenfor.");
    el("step4content", "Hvis din printer er konfigureret, men ikke vises i HP-appen, skal du tilføje din nye printer fra dit netværk. Vælg <strong>Tilføj printer/enhed</strong>.");
    el("step5content", "På mobilenheder skal du trykke på <strong>Afslut nu</strong>, hvis din printer allerede er forbundet til et netværk. På det næste skærmbillede skal du vælge din printer på listen over tilgængelige printere på dit netværk.");
    el("step5content2", "På computere skal du vælge din printer på listen over tilgængelige printere på dit netværk.");
    el("step5subcontent1", "Du sendes tilbage til startskærmen, når din printer er blevet føjet til HP-appen.");
    el("step6content", "Når din nye printer vises i HP-appen, skal du vælge Instant Ink-feltet og derefter vælge knappen <strong>Kom i gang</strong> på det næste skærmbillede for at starte udskiftning af printeren.");
    el("step7content1", "<strong>Printerudskiftninger uden for garanti:</strong>");
    el("step7content1Text", "For udskiftningsprintere uden for garantiordningen skal du, når du bliver bedt om det, vælge indstillingen til udskiftning af printer og derefter vælge <strong>Fortsæt</strong>.");
    el("step7subcontent1", "Skærmbillede for udskiftning uden for garanti");
    el("step7content2", "<strong>Printerudskiftninger inden for garanti:</strong>");
    el("step7content2Text", "For udskiftningsprintere inden for garantiordningen skal du vælge <strong>Fortsæt</strong> for at fortsætte med at tilmelde din nye garantiprinter.");
    el("step7subcontent2", "Skærmbillede for garantiudskiftning");
    el("step8content", "Gennemgå dine Instant Ink-kontooplysninger. Når du er klar, skal du vælge <strong>Fortsæt</strong> for at færdiggøre tilføjelsen af printerudskiftningen.");
    el("deepviewprivacy", "Beskyttelse af dine personlige oplysninger");
    el("deepviewcontent", "Vi bruger cookies (eller tilsvarende teknologi) til at give dig en personlig oplevelse. Når du åbner linket i HP -appen, accepterer du dette og at oplysninger <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Disse data indsamler vi)</u></b></a> om, hvordan du benytter vores websted, bliver delt med vores affilierede og partnere. Du kan administrere dine præferencer og til enhver tid trække dit samtykke tilbage samt finde ud af mere om, <a href='https://www.hp.com/privacy' target='_blank'><b><u>Brug af cookies</u></b></a>, i Cookie-indstillinger.");
} else if ("cs" == userLang || "cs-CZ" == userLang) {
    el("instruction1", "V dalším kroku potřebujeme najít tiskárnu v místní síti.");
    el("instruction2", "Webové prohlížeče z bezpečnostních důvodů nepovolují webovým stránkám přístup k místním zařízením.");
    el("instruction3", "Aplikace HP dokáže bezpečně propojit tiskárnu v místní síti se službou HP Instant Ink v cloudu.");
    el("hideaction", "Zavřít");
    phoneElement.innerHTML = "225 296 667";
    phoneElement.href = "tel:225 296 667";
    el("headline", "Dokončení výměny tiskárny pomocí aplikace HP");
    el("title", "Nemáte v tomto zařízení nainstalovanou aplikaci HP?");
    el("subtitle", "Pokud v tomto zařízení nemáte nainstalovanou aplikaci HP, vyberte možnost <strong>Získat aplikaci HP</strong> a podle níže uvedených pokynů dokončete nastavení služby");
    document.querySelector(".gethpsmart").innerHTML = "Získat aplikaci HP";
    let J = document.querySelectorAll(".apptext");
    for (let B of J) B.innerHTML = "Proč potřebuji tuto aplikaci?";
    el("inksetup", "Pokyny k výměně pro nové tiskárny");
    el("step1content", "Před otevřením aplikace HP si přečtěte všechny níže uvedené pokyny. Tato karta zůstane otevřená v prohlížeči a bude vás provázet postupem výměny.");
    el("step2content", "Pokud budete vyzváni, přihlaste se ke svému stávajícímu účtu. Ujistěte se, že jste přihlášeni k účtu, který používáte pro účely stávajícího předplatného služby Instant Ink.");
    el("step3content", "Pokud již byla nahrazující nová tiskárna nastavena a je aktuálně zobrazena v aplikaci HP, přejděte ke kroku 6 níže.");
    el("step4content", "Pokud je tiskárna nastavena, ale v aplikaci HP se nezobrazuje, je třeba novou nahrazující tiskárnu přidat ze sítě. Zvolte <strong>přidat tiskárnu/zařízení</strong>.");
    el("step5content", "Pokud je tiskárna již připojena k síti, na mobilním zařízení klepněte na možnost <strong>Dokončit</strong>. Na další obrazovce vyberte tiskárnu ze seznamu dostupných tiskáren v síti.");
    el("step5content2", "V počítači vyberte tiskárnu ze seznamu dostupných tiskáren v síti.");
    el("step5subcontent1", "Po přidání tiskárny do aplikace HP se vrátíte na domovskou obrazovku.");
    el("step6content", "Jakmile se nahrazující tiskárna zobrazí v aplikaci HP, vyberte dlaždici Instant Ink a na další obrazovce vyberte tlačítko <strong>Začít</strong>, čímž zahájíte výměnu tiskárny.");
    el("step7content1", "<strong>Nezáruční výměny tiskáren:</strong>");
    el("step7content1Text", "V případě nezáručních výměn tiskáren po zobrazení výzvy vyberte možnost Vyměnit tiskárnu a poté vyberte možnost <strong>Pokračovat</strong>.");
    el("step7subcontent1", "Obrazovka nezáruční výměny");
    el("step7content2", "<strong>Záruční výměny tiskáren:</strong>");
    el("step7content2Text", "V případě záručních výměn tiskáren vyberte možnost <strong>Pokračovat</strong> a pokračujte v registraci tiskárny, kterou jste obdrželi v rámci záruční výměny.");
    el("step7subcontent2", "Obrazovka záruční výměny");
    el("step8content", "Zkontrolujte informace o svém účtu Instant Ink. Výměnu tiskárny dokončete výběrem možnosti <strong>Pokračovat</strong>.");
    el("deepviewprivacy", "Vaše soukromí");
    el("deepviewcontent", "Používáme soubory cookie (nebo podobné technologie), abychom vám přizpůsobili obsah. Otevřením tohoto odkazu v aplikaci HP vyjadřujete souhlas s touto skutečností a s tím, že budeme s našimi přidruženými společnostmi a partnery sdílet informace <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Jaké údaje shromažďujeme)</u></b></a> o tom, jak používáte naše stránky. V Nastavení souborů cookie můžete spravovat své předvolby, kdykoli odvolat svůj souhlas nebo se dozvědět více o <a href='https://www.hp.com/privacy' target='_blank'><b><u>Používání souborů cookie</u></b></a>.");
} else if ("hu" == userLang || "hu-HU" == userLang) {
    el("instruction1", "A következő lépésben meg kell keresnünk a nyomtatót a helyi hálózaton.");
    el("instruction2", "Biztonsági okokból a webböngészők nem engedik, hogy a webhelyek lássák a helyi eszközöket.");
    el("instruction3", "A HP alkalmazás biztonságosan csatlakoztatja a nyomtatót a helyi hálózathoz és a felhőalapú HP Instant Ink szolgáltatáshoz.");
    el("hideaction", "Bezárás");
    phoneElement.innerHTML = "06 1 328 5621";
    phoneElement.href = "tel:06 1 328 5621";
    el("headline", "Fejezd be nyomtatód cseréjét a HP alkalmazással");
    el("title", "Nincs telepítve a HP alkalmazás erre az eszközre?");
    el("subtitle", "Ha ezen az eszközön nincs telepítve a HP alkalmazás, válaszd a <strong>HP alkalmazás beszerzése</strong> lehetőséget, majd kövesd az alábbi utasításokat az Instant Ink beállításának befejezéséhez.");
    document.querySelector(".gethpsmart").innerHTML = "A HP alkalmazás beszerzése";
    let R = document.querySelectorAll(".apptext");
    for (let Q of R) Q.innerHTML = "Miért kell egy alkalmazást használnom?";
    el("inksetup", "Utasítások a cseréhez új nyomtatók esetén");
    el("step1content", "Olvasd végig az instrukciókat, mielőtt megnyitnád a HP alkalmazást. Ez a lap nyitva marad a böngésződben, és segít végighaladni a csere folyamatán.");
    el("step2content", "Amennyiben a rendszer ezt kéri, jelentkezz be meglévő fiókodba. Mindenképpen ugyanabba a fiókba jelentkezz be, mint amelyet a meglévő Instant Ink előfizetésedhez is használsz.");
    el("step3content", "Amennyiben az új nyomtatód már telepítve van, és jelenleg látható a HP alkalmazásban, ugorj az alábbi 6. pontra.");
    el("step4content", "Amennyiben a nyomtatód már telepítve van, de még nem jelenik meg a HP alkalmazásban, hozzá kell adnod az új nyomtatót a hálózatodból. Válaszd a <strong>Nyomtató/eszköz hozzáadása</strong> lehetőséget.");
    el("step5content", "Mobileszközökön koppints a <strong>Befejezés most</strong> lehetőségre, ha a nyomtatód már csatlakozik a hálózathoz. A következő képernyőn válaszd ki a nyomtatódat a hálózatodon elérhető nyomtatók listájából.");
    el("step5content2", "Számítógépen válaszd ki a nyomtatódat a hálózatodon elérhetők közül.");
    el("step5subcontent1", "A nyomtató HP alkalmazáshoz történő hozzáadását követően a rendszer visszairányít a főoldalra.");
    el("step6content", "Amint a nyomtatód megjelenik a HP alkalmazásban, válaszd az Instant Ink csempét, majd a következő kijelzőn válaszd a <strong>Kezdés</strong> gombot a nyomtató cseréjéhez.");
    el("step7content1", "<strong>Nem jótállás keretében cserélt nyomtató:</strong>");
    el("step7content1Text", "A nem jótállás keretében cserélt nyomtatók esetén válaszd a Nyomtató cseréje, majd a <strong>Folytatás</strong> lehetőséget, ha erre kér a rendszer.");
    el("step7subcontent1", "A nem jótállás keretében történő csere képernyője");
    el("step7content2", "<strong>Jótállás keretében cserélt nyomtató:</strong>");
    el("step7content2Text", "A jótállás keretében cserélt nyomtató esetén válaszd a <strong>Folytatás</strong> lehetőséget a jótállás keretében cserélt nyomtatód regisztrálásának folytatásához.");
    el("step7subcontent2", "Jótállás keretében történő csere képernyője");
    el("step8content", "Tekintsd át Instant Ink-fiókod adatait. Ha készen állsz, válaszd a <strong>Folytatás</strong> lehetőséget a nyomtató cseréjének befejezéséhez.");
    el("deepviewprivacy", "Az Ön adatvédelme");
    el("deepviewcontent", "A személyre szabott felhasználói élmény biztosításához cookie-kat (vagy hasonló technológiákat) használunk. Ha megnyitja ezt a hivatkozást a HP alkalmazásban, tudomásul veszi ezt, valamint hogy megosztunk bizonyos információkat <a href='https://www.hp.com/privacy' target='_blank'><b><u>(Milyen adatokat gyűjtünk)</u></b></a> a társvállalatainkkal és partnereinkkel a webhelyünk Ön általi használatáról. A Cookie-beállítások között kezelheti a beállításait, bármikor visszavonhatja a beleegyezését, illetve többet tudhat meg a <a href='https://www.hp.com/privacy' target='_blank'><b><u>Cookie-k használatáról</u></b></a>.");
}